TPFinalGrupo4/Controllers/ReservasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TPFinalGrupo4.Data;
using System.Media;

namespace TPFinalGrupo4.Models
{
    [Authorize]
    public class ReservasController : Controller
    {
        private readonly UsuarioContext _context;
        private SoundPlayer _soundPlayer;

        public ReservasController(UsuarioContext context)
        {
            _context = context;
        }

        // GET: Reservas
      
        public async Task<IActionResult> Index()
        {
            if (!this._context.Usuario.Find(int.Parse(User.Identity.Name)).IsAdmin)
                return Redirect("/Alojamientoes/all?message=No-tenes-permiso-de-administrador");
            return View(await _context.Reserva.Include(r => r.Alojamiento).Include(r => r.Usuario).ToListAsync());
        }

        // GET: Reservas
        public async Task<IActionResult> List()
        {
            var reservas = from reserva in this._context.Reserva.Include(r => r.Alojamiento) select reserva;

            reservas = reservas.Where(reserva => reserva.Usuario.Id == Int32.Parse(@User.Identity.Name));

            return View(reservas.ToList());
        }

        // GET: Reservas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reserva = await _context.Reserva.Include(r => r.Alojamiento).Include(r => r.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reserva == null)
            {
                return NotFound();
            }

            return View(reserva);
        }

        // GET: Reservas/Create
        [HttpGet]
        public IActionResult Create(int? id, String? message)
        {
            if (id == null) return NotFound();
            var alojamiento = this._context.Alojamiento.FirstOrDefaultAsync(alojamiento => alojamiento.Id == id).Result;
            if (alojamiento == null) return NotFound();

            ViewData["message"] = null;
            if (message != null)
                ViewData["message"] = message.Replace("-", " ");

            ViewData["alojamiento_id"] = alojamiento.Id;
            ViewData["alojamiento_ciudad"] = alojamiento.Ciudad;
            ViewData["alojamiento_barrio"] = alojamiento.Barrio;
            ViewData["alojamiento_estrellas"] = alojamiento.Estrellas;
            ViewData["alojamiento_cantidadDePersonas"] = alojamiento.CantidadDePersonas;
            ViewData["alojamiento_tv"] = alojamiento.Tv;
            ViewData["alojamiento_tipo"] = alojamiento.Tipo;
            ViewData["alojamiento_precioPorPersona"] = alojamiento.PrecioPorPersona;
            ViewData["alojamiento_precioPorDia"] = alojamiento.PrecioPorDia;
            ViewData["alojamiento_habitaciones"] = alojamiento.Habitaciones;
            ViewData["alojamiento_banios"] = alojamiento.Banios;

            double precio = 0;
            if (alojamiento.Tipo == "Hotel")
            {
                precio = alojamiento.CantidadDePersonas * alojamiento.PrecioPorPersona;
            }
            else
            {
                precio = alojamiento.PrecioPorDia;
            }

            ViewData["precioTotal"] = precio;

            return View();
        }

        // POST: Reservas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DateTime fechaDesde, DateTime fechaHasta, int id_alojamiento)
        {
            if (!this.DisponibilidadPorFechas(id_alojamiento, fechaDesde, fechaHasta))
            {
                _soundPlayer = new SoundPlayer("Resources/ErrorSound.wav");
                _soundPlayer.Play();
                return Redirect("/Reservas/Create?id=" + id_alojamiento +"&message=El-alojamiento-no-esta-disponible-en-esas-fechas");
            }

            var usuario = this._context.Usuario.Find(int.Parse(User.Identity.Name));
            var alojamiento = await this._context.Alojamiento.FindAsync(id_alojamiento);
            int dias_reservados = (fechaHasta - fechaDesde).Days;

            double precio = dias_reservados * alojamiento.PrecioPorDia;
            if (alojamiento.Tipo == "Hotel")
                precio = dias_reservados * alojamiento.CantidadDePersonas * alojamiento.PrecioPorPersona;

            var reserva = new Reserva
            {
                FechaDesde = fechaDesde,
                FechaHasta = fechaHasta,
                Alojamiento = alojamiento,
                Precio = precio,
                Usuario = usuario
            };

            this._context.Reserva.Add(reserva);
            this._context.SaveChanges();
            _soundPlayer = new SoundPlayer("Resources/SuccessSound.wav");
            _soundPlayer.Play();
            return Redirect("/Reservas/List");
        }

        // GET: Reservas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var reserva = await _context.Reserva.FindAsync(id);
            var todasLasreserva = await _context.Reserva.Include(r => r.Alojamiento).Include(r => r.Usuario).ToListAsync();
            var reserva = todasLasreserva.Find(r => r.Id == id);

            if (reserva == null)
                return NotFound();

            ViewData["reserva_id"] = id;
            ViewData["alojamiento_id"] = reserva.Alojamiento.Id;
            return View(reserva);
        }

        // POST: Reservas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int reserva_id, int alojamiento_id, DateTime FechaDesde, DateTime FechaHasta)
        {
            var reserva = this._context.Reserva.Find(reserva_id);
            var alojamiento = this._context.Alojamiento.Find(alojamiento_id);
            var usuario = this._context.Usuario.Find(int.Parse(User.Identity.Name));

            if(reserva == null || alojamiento == null || usuario == null)
            {
                this._soundPlayer = new SoundPlayer("Resources/ErrorSound.wav");
                this._soundPlayer.Play();
                return NotFound();
            }
            int diasDeReservas = (FechaHasta - FechaDesde).Days;
            double precio = alojamiento.Tipo == "Hotel" ? 
                alojamiento.PrecioPorPersona * diasDeReservas : 
                alojamiento.PrecioPorDia * alojamiento.CantidadDePersonas * diasDeReservas;

            try
            {
                reserva.FechaDesde = FechaDesde;
                reserva.FechaHasta = FechaHasta;
                reserva.Precio = precio;
                this._context.Reserva.Update(reserva);
                this._context.SaveChanges();
            }
            catch (Exception)
            {
                this._soundPlayer = new SoundPlayer("Resources/ErrorSound.wav");
                this._soundPlayer.Play();
                return RedirectToAction(nameof(Index));
            }

            this._soundPlayer = new SoundPlayer("Resources/SuccessSound.wav");
            this._soundPlayer.Play();
            return RedirectToAction(nameof(Index));
        }

        // GET: Reservas/Delete/5
        public async Task<IActionResult> Delete(int? id, String? message)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reserva = await _context.Reserva
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reserva == null)
            {
                return NotFound();
            }

            return View(reserva);
        }

        // POST: Reservas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reserva = await _context.Reserva.FindAsync(id);
            _context.Reserva.Remove(reserva);
            await _context.SaveChangesAsync();
            _soundPlayer = new SoundPlayer("Resources/DeleteSound.wav");
            _soundPlayer.Play();
            if (User.IsInRole("Admin"))
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return RedirectToAction(nameof(List));
            }
        }

        private bool ReservaExists(int id)
        {
            return _context.Reserva.Any(e => e.Id == id);
        }

        private bool DisponibilidadPorFechas(int id_alojamiento, DateTime fechaDesde, DateTime fechaHasta)
        {
            foreach (var reserva in this._context.Reserva.Where(r => r.Alojamiento.Id == id_alojamiento).ToList())
            {
                bool validarFechaDesde = DateTime.Compare(reserva.FechaDesde, fechaDesde) == 1 && DateTime.Compare(reserva.FechaDesde, fechaHasta) == 1;
                bool validarFechaHasta = DateTime.Compare(reserva.FechaHasta, fechaDesde) == -1 && DateTime.Compare(reserva.FechaHasta, fechaDesde) == -1;
                if (!validarFechaDesde && !validarFechaHasta)
                    return false;
            }
            return true;
        }
    }
}

TPFinalGrupo4/Views/Alojamientoes/Buscador.cshtml
@model IEnumerable<TPFinalGrupo4.Models.Alojamiento>

@{
    ViewData["Title"] = "Buscador";
}
@inject LanguageService language

<div class="row pt-4">
    <div class="col-12">
        <h1 class="text-center display-4">@language.Getkey("Buscador")</h1>
    </div>
</div>

<hr class="my-3" />

<!-- FORMULARIO DEL BUSCADOR -->
<div class="justify-content-center mt-3">
    <form asp-action="Buscador" method="GET">
        <div class="form-row justify-content-center">

            <!-- CIUDAD -->
            <div class="form-group col-md-2">
                <label for="ciudad">@language.Getkey("Ciudad"): </label>
                <input type="text" name="ciudad" class="form-control" id="ciudad" placeholder="@language.Getkey("Ingrese una ciudad")" >
            </div>

            <!-- TIPO DE ALOJAMIENTO-->
            <div class="form-group col-md-2">
                <label for="tipoDeAlojamiento">@language.Getkey("Tipo"): </label>
                <select id="tipoDeAlojamiento" name="tipoDeAlojamiento" class="form-control" required>
                    <option value="Todos">@language.Getkey("Todos")</option>
                    <option value="Cabaña">@language.Getkey("Cabaña")</option>
                    <option value="Hotel">@language.Getkey("Hotel")</option>
                </select>
            </div>

            <!-- INPUT FECHA DESDE -->
            <div class="form-group col-md-3">
                <label for="fechaDesde" class="control-label">@language.Getkey("Fecha Desde"): </label>
                <input type="date" class="form-control" name="fechaDesde" id="fechaDesde" max="2021-12-31" required />
            </div>

            <!-- INPUT FECHA HASTA -->
            <div class="form-group col-md-3">
                <label for="fechaHasta" class="control-label">@language.Getkey("Fecha Hasta"): </label>
                <input type="date" class="form-control" name="fechaHasta" id="fechaHasta" max="2021-12-31" required />
            </div>

            <!-- BOTON -->
            <div class="form-group col-12 col-md-2 align-self-end">
                <input type="submit" value=@language.Getkey("Buscador") class="btn btn-success" />
            </div>
        </div>
    </form>
</div>
<!-- FIN DEL BUSCADOR-->


<!-- ALOJAMIENTOS -->
<div class="row row-cols-1 row-cols-md-2 mt-4">
    @foreach (var item in Model)
    {
        <div class="col-12 col-md-3 mb-4">
            <div class="card shadow">

                <!-- IMAGEN -->
                @if (item.Tipo == "Hotel")
                {
                    <img src="~/imgs/hotel.jpg" class="card-img-top image-alojamiento-all" alt="Imagen de un hotel">
                }
                else
                {
                    <img src="~/imgs/cabania.jpg" class="card-img-top image-alojamiento-all" alt="Imagen de una cabaña">
                }
                <div class="col mx-0">
                    <div class="card-body">
                        <h5 class="card-title text-capitalize">
                            @Html.DisplayFor(modelItem => item.Tipo)
                        </h5>
                        <p class="card-text text-capitalize mb-0 pb-0">
                            @language.Getkey("Ciudad"): @item.Ciudad
                        </p>
                        <p class="card-text text-capitalize mb-0 pb-0">
                            @language.Getkey("Barrio"): @item.Barrio
                        </p>
                        <p class="card-text mb-0 pb-0">
                            TV @Html.DisplayFor(modelItem => item.Tv) | @Html.DisplayFor(modelItem => item.Estrellas) @language.Getkey("estrellas")
                        </p>
                        <p class="card-text">
                            $
                            @if (item.Tipo == "Hotel")
                            {
                                @Html.DisplayFor(modelItem => item.PrecioPorPersona)
                            }
                            else
                            {
                                @Html.DisplayFor(modelItem => item.PrecioPorDia)
                            }
                        </p>
                        <form asp-controller="Reservas" asp-action="Create" method="POST" class="m-0 p-0">
                            <input type="hidden" name="id_alojamiento" value='@item.Id' />
                            <input type="hidden" name="fechaDesde" id="input_fechaDesde_reserva" value='@ViewData["fechaDesde"]' />
                            <input type="hidden" name="fechaHasta" id="input_fechaHasta_reserva" value='@ViewData["fechaHasta"]' />
                            <button type="submit" class="btn btn-success btn-block">@language.Getkey("Reservar")</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    }
</div>



<!-- VALIDACION DE FECHAS -->
<script type="text/javascript">

    // Fecha actual
    const hoy = moment(new Date()).format('YYYY-MM-DD')

    // Formulario
    const formulario = document.getElementById("formulario-reserva");
    const inputFechaDesde = document.getElementById("fechaDesde")
    const inputFechaHasta = document.getElementById("fechaHasta")
    inputFechaDesde.min = hoy
    inputFechaHasta.min = hoy

    formulario.addEventListener("submit", (e) => {
        e.preventDefault()

        const diasFechaDesde = moment(inputFechaDesde.value).dayOfYear()
        const diasFechaHasta = moment(inputFechaHasta.value).dayOfYear()

        if ((diasFechaHasta - diasFechaDesde) <= 0) {
            alert('Fechas no validas, vuelva a intentarlo')
            formulario.reset()
        } else {
            if (confirm("¿ Desea realizar la reserva ?")) {
                formulario.submit()
            }
        }
    })
</script>
    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

TPFinalGrupo4/Views/Alojamientoes/Create.cshtml
@model TPFinalGrupo4.Models.Alojamiento

@{
    ViewData["Title"] = "Create";
}
@inject LanguageService language
@inject UsuarioContext context

@if (ViewData["message"] != null)
{
    <!-- Mensaje al usuario -->
    <div class="alert alert-danger" role="alert" id="Codigo-incorrecto">
        <strong>@ViewData["message"]</strong>
    </div>
    <script type="text/javascript">
        setTimeout(() => {
            document.getElementById("Codigo-incorrecto").remove()
        }, 4000)
    </script>
}

<h1 class="text-center">@language.Getkey("Crear Alojamiento")</h1>

<hr />
<div class="row">
    <div class="col-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group row">
                <div class="form-group col-4">
                    <label asp-for="Codigo" class="control-label">@language.Getkey("Codigo")</label>
                    <input asp-for="Codigo" class="form-control" />
                    <span asp-validation-for="Codigo" class="text-danger"></span>
                </div>
                <div class="form-group col-4">
                    <label asp-for="Ciudad" class="control-label">@language.Getkey("Ciudad")</label>
                    <select asp-for="Ciudad" class="form-control">
                        @foreach (var item in context.Ciudad)
                        {
                            <option value="@item.ID">@item.Nombre</option>
                        }
                    </select>
                    <span asp-validation-for="Ciudad" class="text-danger"></span>
                </div>
                <div class="form-group col-4">
                    <label asp-for="Barrio" class="control-label">@language.Getkey("Barrio")</label>
                    <input asp-for="Barrio" class="form-control" />
                    <span asp-validation-for="Barrio" class="text-danger"></span>
                </div>

                <div class="form-group col-3">
                    <label asp-for="Estrellas" class="control-label">@language.Getkey("Estrellas")</label>
                    <select asp-for="Estrellas" class="form-control">
                        @for (int i = 1; i <= 5; i++)
                        {
                            <option value="@i">@i</option>
                        }
                    </select>
                    <span asp-validation-for="Estrellas" class="text-danger"></span>
                </div>
                <div class="form-group col-3">
                    <label asp-for="CantidadDePersonas" class="control-label">@language.Getkey("Cantidad de Personas")</label>
                    <select asp-for="CantidadDePersonas" class="form-control">
                        @for (int i = 1; i <= 10; i++)
                        {
                            <option value="@i">@i</option>
                        }
                    </select>
                    <span asp-validation-for="CantidadDePersonas" class="text-danger"></span>
                </div>
                <div class="form-group form-check align-self-center col-3">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="Tv" /> @Html.DisplayNameFor(model => model.Tv)
                    </label>
                </div>
                <div class="form-group col-3">
                    <label asp-for="Tipo" class="control-label">@language.Getkey("Tipo")</label>
                    <select asp-for="Tipo" class="form-control">
                        <option value="Hotel">@language.Getkey("Hotel")</option>
                        <option value="Cabaña">@language.Getkey("Cabaña")</option>
                    </select>
                    <span asp-validation-for="Tipo" class="text-danger"></span>
                </div>
                <div class="form-group col-12">
                    <label asp-for="PrecioPorPersona" class="control-label">@language.Getkey("Precio por Persona")</label>
                    <input asp-for="PrecioPorPersona" class="form-control" />
                    <span asp-validation-for="PrecioPorPersona" class="text-danger"></span>
                </div>

                <div class="form-group col-4">
                    <label asp-for="PrecioPorDia" class="control-label">@language.Getkey("Precio por Dia")</label>
                    <input asp-for="PrecioPorDia" class="form-control" />
                    <span asp-validation-for="PrecioPorDia" class="text-danger"></span>
                </div>
                <div class="form-group col-4">
                    <label asp-for="Habitaciones" class="control-label">@language.Getkey("Habitaciones")</label>
                    <input asp-for="Habitaciones" class="form-control" />
                    <span asp-validation-for="Habitaciones" class="text-danger"></span>
                </div>
                <div class="form-group col-4">
                    <label asp-for="Banios" class="control-label">@language.Getkey("Baños")</label>
                    <input asp-for="Banios" class="form-control" />
                    <span asp-validation-for="Banios" class="text-danger"></span>
                </div>

                <div class="form-group col-12">
                    <input type="submit" value="@language.Getkey("Crear")" class="btn btn-success" />
                    <a asp-action="Index" class="btn btn-primary">@language.Getkey("Volver")</a>
                </div>
            </div>
        </form>
    </div>
</div>

<div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TPFinalGrupo4/Views/Alojamientoes/Delete.cshtml
@model TPFinalGrupo4.Models.Alojamiento

@{
    ViewData["Title"] = "Delete";
}
@inject LanguageService language

<h1 class="text-center">@language.Getkey("Borrar Alojamiento")</h1>

<h3 class="text-center">@language.Getkey("¿Está seguro de querer borrar este alojamiento?")</h3>
<hr class="my-4" />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @language.Getkey("Codigo")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
        <dt class="col-sm-2">
            @language.Getkey("Ciudad")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ciudad)
        </dd>
        <dt class="col-sm-2">
            @language.Getkey("Barrio")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Barrio)
        </dd>
        <dt class="col-sm-2">
            @language.Getkey("Estrellas")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Estrellas)
        </dd>
        <dt class="col-sm-2">
            @language.Getkey("Cantidad de Personas")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CantidadDePersonas)
        </dd>
        <dt class="col-sm-2">
            @language.Getkey("Tv")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tv)
        </dd>
        <dt class="col-sm-2">
            @language.Getkey("Tipo")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dt class="col-sm-2">
            @language.Getkey("Precio por Persona")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PrecioPorPersona)
        </dd>
        <dt class="col-sm-2">
            @language.Getkey("Precio por Dia")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PrecioPorDia)
        </dd>
        <dt class="col-sm-2">
            @language.Getkey("Habitaciones")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Habitaciones)
        </dd>
        <dt class="col-sm-2">
            @language.Getkey("Baños")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Banios)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-danger"><i class="fas fa-trash-alt mr-2"></i>@language.Getkey("Borrar")</button>
        <a asp-action="Index" class="btn btn-primary">@language.Getkey("Volver")</a>
    </form>
</div>

TPFinalGrupo4/Views/Alojamientoes/all.cshtml
@model IEnumerable<TPFinalGrupo4.Models.Alojamiento>

@{
    ViewData["Title"] = "Alojamientos";
}
@inject LanguageService language


@if (ViewData["message"] != null)
{
    <!-- Mensaje al usuario -->
    <div class="alert alert-danger" role="alert" id="alert-message-permisos">
        <strong>@ViewData["message"]</strong>
    </div>
    <script type="text/javascript">
        setTimeout(() => {
            document.getElementById("alert-message-permisos").remove()
        }, 4000)
    </script>
}

<div class="row pt-4">
    <div class="col-12">
        <h1 class="text-center display-4">@language.Getkey("Alojamientos")</h1>
    </div>
</div>

<hr class="my-3" />

<!-- FORMULARIO PARA EL FILTRO -->
<div class="justify-content-center mt-3">
    <form asp-action="all">
        <div class="form-row justify-content-center">
            <div class="form-group col-md-3">
                <label>@language.Getkey("Precio"): </label>
                <input type="number" name="precio" class="form-control" id="precio" placeholder="@language.Getkey("Ingrese el precio mínimo")" required>
            </div>
            <div class="form-group col-md-3">
                <label>@language.Getkey("Cantidad de Estrellas"): </label>
                <select id="estrellas" name="estrellas" class="form-control" required>
                    <option value="" selected>-- @language.Getkey("Minimas estrellas") --</option>
                    @for (int i = 1; i <= 5; i++)
                    {
                        <option value="@i">@i</option>
                    }
                </select>
            </div>
            <div class="form-group col-md-4">
                <label>@language.Getkey("Cantidad de Personas"): </label>
                <select id="cantidadDePersonas" name="cantidadDePersonas" class="form-control" required>
                    <option value="" selected>-- @language.Getkey("Minima cantidad de personas") --</option>
                    @for (int i = 1; i <= 10; i++)
                    {
                        <option value="@i">@i</option>
                    }
                </select>
            </div>
            <div class="form-group col-md-2 align-self-end">
                <button type="submit" class="btn btn-outline-primary btn-block"><i class="fas fa-filter"></i> @language.Getkey("Filtrar")</button>
            </div>
        </div>
    </form>
</div>

<div class="row row-cols-1 row-cols-md-2 mt-4">
    @foreach (var item in Model)
    {
        <div class="col-12 col-md-3 mb-4 ">
            <div class="card shadow">

                <!-- IMAGEN -->
                @if (item.Tipo == "Hotel")
                {
                    <img src="~/imgs/hotel.jpg" class="card-img-top image-alojamiento-all" alt="Imagen de un hotel">
                }
                else
                {
                    <img src="~/imgs/cabania.jpg" class="card-img-top image-alojamiento-all" alt="Imagen de una cabaña">
                }
                <div class="col mx-0">
                    <div class="card-body">
                        <h5 class="card-title text-capitalize">
                            @Html.DisplayFor(modelItem => item.Tipo)
                        </h5>
                        <p class="card-text text-capitalize mb-0 pb-0">
                            @language.Getkey("Ciudad"): @item.Ciudad
                        </p>
                        <p class="card-text text-capitalize mb-0 pb-0">
                            @language.Getkey("Barrio"): @item.Barrio
                        </p>
                        <p class="card-text mb-0 pb-0">
                            TV @Html.DisplayFor(modelItem => item.Tv) | @Html.DisplayFor(modelItem => item.Estrellas) @language.Getkey("estrellas")
                        </p>
                        <p class="card-text">
                            $
                            @if (item.Tipo == "Hotel")
                            {
                                @Html.DisplayFor(modelItem => item.PrecioPorPersona)
                            }
                            else
                            {
                                @Html.DisplayFor(modelItem => item.PrecioPorDia)
                            }
                        </p>
                        <!-- Link a detalle del alojamiento -->
                        <a asp-route-id="@item.Id"
                           asp-controller="Reservas"
                           asp-action="Create"
                           class="btn btn-success btn-block px-5">
                            <i class="fas fa-search mr-2"></i>
                            @language.Getkey("Ver")
                        </a>
                    </div>
                </div>
            </div>
        </div>
    }
</div>